# Form implementation generated from reading ui file 'ui_combo_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ComboDialog(object):
    def setupUi(self, ComboDialog):
        ComboDialog.setObjectName("ComboDialog")
        ComboDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        ComboDialog.resize(513, 194)
        ComboDialog.setModal(True)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=ComboDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 488, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 1, 1, 1)
        self.pushAccept = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushAccept.sizePolicy().hasHeightForWidth())
        self.pushAccept.setSizePolicy(sizePolicy)
        self.pushAccept.setMinimumSize(QtCore.QSize(52, 52))
        self.pushAccept.setObjectName("pushAccept")
        self.gridLayout.addWidget(self.pushAccept, 1, 0, 1, 1)
        self.pushReject = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushReject.sizePolicy().hasHeightForWidth())
        self.pushReject.setSizePolicy(sizePolicy)
        self.pushReject.setMinimumSize(QtCore.QSize(52, 52))
        self.pushReject.setObjectName("pushReject")
        self.gridLayout.addWidget(self.pushReject, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(ComboDialog)
        QtCore.QMetaObject.connectSlotsByName(ComboDialog)

    def retranslateUi(self, ComboDialog):
        _translate = QtCore.QCoreApplication.translate
        ComboDialog.setWindowTitle(_translate("ComboDialog", "Dialog"))
        self.pushAccept.setText(_translate("ComboDialog", "accept"))
        self.pushReject.setText(_translate("ComboDialog", "reject"))
        self.label.setText(_translate("ComboDialog", "TextLabel"))
